### ISSUE TITLE
Drone.io does not support scala 2.11

### ISSUE THREAD

**Issue by calippo** [buildo/ci#1]
## description
Drone.io supports only scala `2.8` and `2.9`. For this reason I'm currently running mailo's tests (https://github.com/buildo/mailo) on travis-ci instead of drone.io.

- Are we planning to deploy our self-hosted version of drone to have CI in projects other than aliniq?
- Is there any turnaround? (I tried to play with the configs for a while but I was not able to address the problem)

## how to reproduce
http://docs.drone.io/scala.html

**Comment by gabro** [comment]
drone.io is the hosted version that's no longer maintained.
We're using the open-source version, installed on our machines. So, yes, it already supports whatever scala version you want.

Refer to http://readme.drone.io (and not docs.drone.io) and login [here](drone.our.buildo.io) to enable to repository.

**Comment by calippo** [comment]
@gabro ok great, I thought this was only for aliniq.

**Comment by gabro** [comment]
Nope. We have two versions deployed (one for github.com and one for github enteprise), and you can configure any repo on it.

I've added a note about drone.io in the README because I got confused too at the beginning.
